import {
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  signOut,
  sendPasswordResetEmail,
  GoogleAuthProvider,
  signInWithPopup,
  onAuthStateChanged,
  type User,
  type UserCredential,
} from 'firebase/auth';
import { doc, getDoc, setDoc, updateDoc, serverTimestamp } from 'firebase/firestore';
import { getFirebaseAuth, getFirebaseFirestore } from './config';
import { mapAuthErrorToArabic } from './mapAuthError';
import type { AccountType } from '../auth/account';
import { fields, toIso } from './docData';

const DEFAULT_PREFERENCES: AuthUser['preferences'] = {
  language: 'ar',
  notifications: { email: true, sms: true, push: true },
  privacy: { showPhone: true, showEmail: false, showLastSeen: true },
};

function splitName(fullName: string): { firstName: string; lastName: string } {
  const parts = fullName.trim().split(/\s+/);
  return {
    firstName: parts[0] || fullName,
    lastName: parts.slice(1).join(' '),
  };
}

export type RegisterProfileInput = {
  displayName?: string;
  name?: string;
  phoneNumber?: string;
  phone?: string;
  firstName?: string;
  lastName?: string;
  wilaya?: string;
  commune?: string;
  email?: string;
  accountType?: AccountType;
  profileComplete?: boolean;
};

function withAliases(user: Omit<AuthUser, 'name' | 'phone'> & Partial<Pick<AuthUser, 'name' | 'phone'>>): AuthUser {
  return {
    ...user,
    name: user.name || user.displayName,
    phone: user.phone || user.phoneNumber,
  };
}

function defaultUserFields(overrides: Partial<AuthUser> & Pick<AuthUser, 'id' | 'email' | 'displayName'>): AuthUser {
  const displayName = overrides.displayName;
  const phoneNumber = overrides.phoneNumber || overrides.phone || '';
  const names = splitName(displayName);
  const base: AuthUser = {
    id: overrides.id,
    email: overrides.email,
    displayName,
    phoneNumber,
    name: displayName,
    phone: phoneNumber,
    firstName: overrides.firstName || names.firstName,
    lastName: overrides.lastName ?? names.lastName,
    gender: overrides.gender || 'not_specified',
    wilaya: overrides.wilaya || '',
    commune: overrides.commune || '',
    isEmailVerified: overrides.isEmailVerified ?? false,
    isPhoneVerified: overrides.isPhoneVerified ?? false,
    listingsCount: overrides.listingsCount ?? 0,
    totalViews: overrides.totalViews ?? 0,
    totalContactClicks: overrides.totalContactClicks ?? 0,
    rating: overrides.rating ?? 0,
    reviewsCount: overrides.reviewsCount ?? 0,
    accountStatus: overrides.accountStatus || 'active',
    role: overrides.role || 'user',
    accountType: overrides.accountType,
    profileComplete: overrides.profileComplete ?? false,
    isSubscribedToNewsletter: overrides.isSubscribedToNewsletter ?? false,
    memberSince: overrides.memberSince || new Date().toISOString(),
    socialLinks: overrides.socialLinks || {},
    preferences: overrides.preferences || DEFAULT_PREFERENCES,
  };
  if (overrides.profileImageUrl) base.profileImageUrl = overrides.profileImageUrl;
  if (overrides.lastLoginAt) base.lastLoginAt = overrides.lastLoginAt;
  if (overrides.dateOfBirth) base.dateOfBirth = overrides.dateOfBirth;
  if (overrides.address) base.address = overrides.address;
  if (overrides.bio) base.bio = overrides.bio;
  if (overrides.website) base.website = overrides.website;
  return base;
}

export interface AuthUser {
  // معرف المستخدم (auto-generated by Firebase Auth)
  id: string; // Firebase UID
  
  // المعلومات الأساسية
  email: string; // البريد الإلكتروني
  displayName: string; // الاسم الكامل
  phoneNumber: string; // رقم الهاتف (+213XXXXXXXXX)
  /** توافق عكسي مع الواجهات الحالية */
  name: string;
  /** توافق عكسي مع الواجهات الحالية */
  phone: string;
  
  // المعلومات الشخصية
  firstName: string; // الاسم الأول
  lastName: string; // اسم العائلة
  dateOfBirth?: string; // تاريخ الميلاد (اختياري) - ISO string
  gender: 'male' | 'female' | 'not_specified'; // الجنس
  
  // الموقع الجغرافي
  wilaya: string; // الولاية
  commune: string; // البلدية
  address?: string; // العنوان التفصيلي (اختياري)
  
  // معلومات الحساب
  profileImageUrl?: string; // رابط صورة الملف الشخصي
  isEmailVerified: boolean; // تأكيد البريد الإلكتروني
  isPhoneVerified: boolean; // تأكيد رقم الهاتف
  
  // الإحصائيات
  listingsCount: number; // عدد الإعلانات
  totalViews: number; // إجمالي المشاهدات
  totalContactClicks: number; // إجمالي النقرات على الاتصال
  rating: number; // التقييم (1-5)
  reviewsCount: number; // عدد التقييمات
  
  // الحالة والصلاحيات
  accountStatus: 'active' | 'suspended' | 'pending'; // حالة الحساب
  role: 'user' | 'admin' | 'moderator'; // الدور
  accountType?: AccountType; // نوع الحساب: مشتري / بائع عادي / تاجر
  profileComplete?: boolean; // هل أكمل الملف بعد التسجيل
  isSubscribedToNewsletter: boolean; // الاشتراك في النشرة
  
  // التواريخ
  memberSince: string; // تاريخ إنشاء الحساب - ISO string
  lastLoginAt?: string; // آخر تسجيل دخول - ISO string
  
  // معلومات إضافية
  bio?: string; // نبذة شخصية (اختياري)
  website?: string; // الموقع الإلكتروني (اختياري)
  socialLinks: {
    facebook?: string;
    instagram?: string;
    whatsapp?: string;
  };
  
  // الإعدادات
  preferences: {
    language: 'ar' | 'en' | 'fr'; // اللغة
    notifications: {
      email: boolean;
      sms: boolean;
      push: boolean;
    };
    privacy: {
      showPhone: boolean;
      showEmail: boolean;
      showLastSeen: boolean;
    };
  };
}

/**
 * Sign in with email and password
 */
export async function signInWithEmail(email: string, password: string): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const result = await signInWithEmailAndPassword(auth, email, password);
    
    // Get user profile from Firestore
    const userProfile = await getUserProfile(result.user.uid);
    if (!userProfile) {
      throw new Error('ملف المستخدم غير موجود');
    }
    return userProfile;
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Create account with email and password
 */
export async function registerWithEmail(
  email: string,
  password: string,
  profile: RegisterProfileInput
): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const result = await createUserWithEmailAndPassword(auth, email, password);
    const displayName = profile.displayName || profile.name || 'مستخدم';
    const phoneNumber = profile.phoneNumber || profile.phone || '';
    const names = splitName(displayName);

    const userProfile = defaultUserFields({
      id: result.user.uid,
      email,
      displayName,
      phoneNumber,
      firstName: profile.firstName || names.firstName,
      lastName: profile.lastName ?? names.lastName,
      wilaya: profile.wilaya || '',
      commune: profile.commune || '',
      accountType: profile.accountType,
      profileComplete: profile.profileComplete ?? Boolean(profile.wilaya && profile.phoneNumber),
    });
    
    await createUserProfile(userProfile);
    return userProfile;
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Sign in with Google
 */
export async function signInWithGoogle(): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const provider = new GoogleAuthProvider();
    provider.addScope('email');
    provider.addScope('profile');
    
    const result = await signInWithPopup(auth, provider);
    
    // Check if user profile exists, create if not
    let userProfile = await getUserProfile(result.user.uid, false);
    
    if (!userProfile) {
      const displayName = result.user.displayName || 'مستخدم جوجل';
      const photoURL = result.user.photoURL;
      userProfile = defaultUserFields({
        id: result.user.uid,
        email: result.user.email || '',
        displayName,
        phoneNumber: result.user.phoneNumber || '',
        isEmailVerified: result.user.emailVerified,
        profileComplete: false,
        lastLoginAt: new Date().toISOString(),
        ...(photoURL ? { profileImageUrl: photoURL } : {}),
      });
      
      await createUserProfile(userProfile);
    } else {
      // Update last login for existing users
      await updateUserProfile(userProfile.id, { 
        lastLoginAt: new Date().toISOString() 
      });
      userProfile.lastLoginAt = new Date().toISOString();
    }
    
    return userProfile;
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Sign out current user
 */
export async function signOutUser(): Promise<void> {
  try {
    const auth = getFirebaseAuth();
    await signOut(auth);
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Send password reset email
 */
export async function sendPasswordReset(email: string): Promise<void> {
  try {
    const auth = getFirebaseAuth();
    await sendPasswordResetEmail(auth, email);
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Set up auth state listener
 */
export function onAuthStateChange(callback: (user: User | null) => void): () => void {
  const auth = getFirebaseAuth();
  return onAuthStateChanged(auth, callback);
}

/**
 * Get current Firebase user
 */
export function getCurrentUser(): User | null {
  const auth = getFirebaseAuth();
  return auth.currentUser;
}

/**
 * Get user profile from Firestore
 */
export async function getUserProfile(uid: string, throwIfNotFound = true): Promise<AuthUser | null> {
  try {
    const firestore = getFirebaseFirestore();
    const userDoc = await getDoc(doc(firestore, 'users', uid));
    
    if (!userDoc.exists()) {
      if (throwIfNotFound) {
        throw new Error('ملف المستخدم غير موجود');
      }
      return null;
    }
    
    const data = fields(userDoc.data());
    const displayName = data['displayName'] || data['name'] || '';
    const phoneNumber = data['phoneNumber'] || data['phone'] || '';
    const names = splitName(displayName);

    const lastLoginAt = toIso(data['lastLoginAt']);

    return withAliases({
      id: data['id'] || uid,
      email: data['email'] || '',
      displayName,
      phoneNumber,
      firstName: data['firstName'] || names.firstName,
      lastName: data['lastName'] || names.lastName,
      ...(data['dateOfBirth'] ? { dateOfBirth: data['dateOfBirth'] } : {}),
      gender: data['gender'] || 'not_specified',
      wilaya: data['wilaya'] || '',
      commune: data['commune'] || '',
      ...(data['address'] ? { address: data['address'] } : {}),
      ...(data['profileImageUrl'] ? { profileImageUrl: data['profileImageUrl'] } : {}),
      isEmailVerified: data['isEmailVerified'] || false,
      isPhoneVerified: data['isPhoneVerified'] || false,
      listingsCount: data['listingsCount'] || 0,
      totalViews: data['totalViews'] || 0,
      totalContactClicks: data['totalContactClicks'] || 0,
      rating: data['rating'] || 0,
      reviewsCount: data['reviewsCount'] || 0,
      accountStatus: data['accountStatus'] || 'active',
      role: data['role'] || 'user',
      accountType: data['accountType'],
      profileComplete:
        data['profileComplete'] ??
        Boolean(displayName?.trim() && phoneNumber?.trim() && data['wilaya'] && data['accountType']),
      isSubscribedToNewsletter: data['isSubscribedToNewsletter'] || false,
      memberSince: toIso(data['memberSince']) || data['memberSince'] || new Date().toISOString(),
      ...(lastLoginAt ? { lastLoginAt } : {}),
      ...(data['bio'] ? { bio: data['bio'] } : {}),
      ...(data['website'] ? { website: data['website'] } : {}),
      socialLinks: data['socialLinks'] || {},
      preferences: data['preferences'] || DEFAULT_PREFERENCES,
    });
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Create user profile in Firestore
 */
export async function createUserProfile(profile: AuthUser): Promise<void> {
  try {
    const firestore = getFirebaseFirestore();
    await setDoc(doc(firestore, 'users', profile.id), {
      ...profile,
      // Legacy fields for backward compatibility
      name: profile.displayName,
      phone: profile.phoneNumber,
      // Timestamps
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Update user profile in Firestore
 */
export async function updateUserProfile(uid: string, updates: Partial<AuthUser>): Promise<void> {
  try {
    const firestore = getFirebaseFirestore();
    
    // Prepare updates with legacy field compatibility
    const updateData: any = {
      ...updates,
      updatedAt: serverTimestamp(),
    };
    
    // Add legacy fields for backward compatibility
    if (updates.displayName || updates.name) {
      updateData.name = updates.displayName || updates.name;
      updateData.displayName = updates.displayName || updates.name;
    }
    if (updates.phoneNumber || updates.phone) {
      updateData.phone = updates.phoneNumber || updates.phone;
      updateData.phoneNumber = updates.phoneNumber || updates.phone;
    }
    
    await updateDoc(doc(firestore, 'users', uid), updateData);
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}