import {
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  signOut,
  sendPasswordResetEmail,
  GoogleAuthProvider,
  signInWithPopup,
  signInWithRedirect,
  getRedirectResult,
  onAuthStateChanged,
  type User,
  type UserCredential,
} from 'firebase/auth';
import { doc, getDoc, setDoc, updateDoc, serverTimestamp } from 'firebase/firestore';
import { getFirebaseAuth, getFirebaseFirestore } from './config';
import { mapAuthErrorToArabic, mapFirebaseErrorToArabic } from './mapAuthError';
import type { AccountType } from '../auth/account';
import { fields, toIso } from './docData';
import { formatAlgerianPhone } from '../validation/rules';

const DEFAULT_PREFERENCES: AuthUser['preferences'] = {
  language: 'ar',
  notifications: { email: true, sms: true, push: true },
  privacy: { showPhone: true, showEmail: false, showLastSeen: true },
};

function splitName(fullName: string): { firstName: string; lastName: string } {
  const parts = fullName.trim().split(/\s+/);
  return {
    firstName: parts[0] || fullName,
    lastName: parts.slice(1).join(' '),
  };
}

export type RegisterProfileInput = {
  displayName?: string;
  name?: string;
  phoneNumber?: string;
  phone?: string;
  firstName?: string;
  lastName?: string;
  wilaya?: string;
  commune?: string;
  email?: string;
  accountType?: AccountType;
  profileComplete?: boolean;
};

function withAliases(user: Omit<AuthUser, 'name' | 'phone'> & Partial<Pick<AuthUser, 'name' | 'phone'>>): AuthUser {
  return {
    ...user,
    name: user.name || user.displayName,
    phone: user.phone || user.phoneNumber,
  };
}

/** Remove undefined values — Firestore setDoc/updateDoc reject them. */
function omitUndefined<T extends Record<string, unknown>>(obj: T): Partial<T> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (value !== undefined) out[key] = value;
  }
  return out as Partial<T>;
}

function defaultUserFields(overrides: Partial<AuthUser> & Pick<AuthUser, 'id' | 'email' | 'displayName'>): AuthUser {
  const displayName = overrides.displayName;
  const phoneNumber = overrides.phoneNumber || overrides.phone || '';
  const names = splitName(displayName);
  const base: AuthUser = {
    id: overrides.id,
    email: overrides.email,
    displayName,
    phoneNumber,
    name: displayName,
    phone: phoneNumber,
    firstName: overrides.firstName || names.firstName,
    lastName: overrides.lastName ?? names.lastName,
    gender: overrides.gender || 'not_specified',
    wilaya: overrides.wilaya || '',
    commune: overrides.commune || '',
    isEmailVerified: overrides.isEmailVerified ?? false,
    isPhoneVerified: overrides.isPhoneVerified ?? false,
    listingsCount: overrides.listingsCount ?? 0,
    totalViews: overrides.totalViews ?? 0,
    totalContactClicks: overrides.totalContactClicks ?? 0,
    rating: overrides.rating ?? 0,
    reviewsCount: overrides.reviewsCount ?? 0,
    accountStatus: overrides.accountStatus || 'active',
    role: overrides.role || 'user',
    profileComplete: overrides.profileComplete ?? false,
    isSubscribedToNewsletter: overrides.isSubscribedToNewsletter ?? false,
    memberSince: overrides.memberSince || new Date().toISOString(),
    socialLinks: overrides.socialLinks || {},
    preferences: overrides.preferences || DEFAULT_PREFERENCES,
  };
  // accountType is set only after complete-profile — never write undefined to Firestore
  if (overrides.accountType) base.accountType = overrides.accountType;
  if (overrides.profileImageUrl) base.profileImageUrl = overrides.profileImageUrl;
  if (overrides.lastLoginAt) base.lastLoginAt = overrides.lastLoginAt;
  if (overrides.dateOfBirth) base.dateOfBirth = overrides.dateOfBirth;
  if (overrides.address) base.address = overrides.address;
  if (overrides.bio) base.bio = overrides.bio;
  if (overrides.website) base.website = overrides.website;
  return base;
}

export interface AuthUser {
  // معرف المستخدم (auto-generated by Firebase Auth)
  id: string; // Firebase UID
  
  // المعلومات الأساسية
  email: string; // البريد الإلكتروني
  displayName: string; // الاسم الكامل
  phoneNumber: string; // رقم الهاتف (+213XXXXXXXXX)
  /** توافق عكسي مع الواجهات الحالية */
  name: string;
  /** توافق عكسي مع الواجهات الحالية */
  phone: string;
  
  // المعلومات الشخصية
  firstName: string; // الاسم الأول
  lastName: string; // اسم العائلة
  dateOfBirth?: string; // تاريخ الميلاد (اختياري) - ISO string
  gender: 'male' | 'female' | 'not_specified'; // الجنس
  
  // الموقع الجغرافي
  wilaya: string; // الولاية
  commune: string; // البلدية
  address?: string; // العنوان التفصيلي (اختياري)
  
  // معلومات الحساب
  profileImageUrl?: string; // رابط صورة الملف الشخصي
  isEmailVerified: boolean; // تأكيد البريد الإلكتروني
  isPhoneVerified: boolean; // تأكيد رقم الهاتف
  
  // الإحصائيات
  listingsCount: number; // عدد الإعلانات
  totalViews: number; // إجمالي المشاهدات
  totalContactClicks: number; // إجمالي النقرات على الاتصال
  rating: number; // التقييم (1-5)
  reviewsCount: number; // عدد التقييمات
  
  // الحالة والصلاحيات
  accountStatus: 'active' | 'suspended' | 'pending' | 'deleted'; // حالة الحساب
  role: 'user' | 'admin' | 'moderator'; // الدور
  accountType?: AccountType; // نوع الحساب: مشتري / بائع عادي / تاجر
  profileComplete?: boolean; // هل أكمل الملف بعد التسجيل
  isSubscribedToNewsletter: boolean; // الاشتراك في النشرة
  
  // التواريخ
  memberSince: string; // تاريخ إنشاء الحساب - ISO string
  lastLoginAt?: string; // آخر تسجيل دخول - ISO string
  
  // معلومات إضافية
  bio?: string; // نبذة شخصية (اختياري)
  website?: string; // الموقع الإلكتروني (اختياري)
  socialLinks: {
    facebook?: string;
    instagram?: string;
    whatsapp?: string;
  };
  
  // الإعدادات
  preferences: {
    language: 'ar' | 'en' | 'fr'; // اللغة
    notifications: {
      email: boolean;
      sms: boolean;
      push: boolean;
    };
    privacy: {
      showPhone: boolean;
      showEmail: boolean;
      showLastSeen: boolean;
    };
  };
}

function assertAccountAllowed(user: AuthUser): void {
  if (user.accountStatus === 'suspended') {
    throw new Error('تم تعليق حسابك. تواصل مع الإدارة إن كان ذلك خطأً.');
  }
  if (user.accountStatus === 'deleted') {
    throw new Error('تم إيقاف هذا الحساب. لا يمكن تسجيل الدخول به.');
  }
}

async function signOutQuietly(): Promise<void> {
  try {
    const auth = getFirebaseAuth();
    await signOut(auth);
  } catch {
    // ignore
  }
}

/**
 * Sign in with email and password
 */
export async function signInWithEmail(email: string, password: string): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const result = await signInWithEmailAndPassword(auth, email, password);
    
    // Recreate Firestore profile if Auth exists but profile was hard-deleted (legacy)
    let userProfile = await getUserProfile(result.user.uid, false);
    if (!userProfile) {
      userProfile = defaultUserFields({
        id: result.user.uid,
        email: result.user.email || email,
        displayName: result.user.displayName || email.split('@')[0] || 'مستخدم',
        isEmailVerified: result.user.emailVerified,
        profileComplete: false,
        lastLoginAt: new Date().toISOString(),
      });
      await createUserProfile(userProfile);
    }

    try {
      assertAccountAllowed(userProfile);
    } catch (blocked) {
      await signOutQuietly();
      throw blocked;
    }
    return userProfile;
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Create account with email and password
 */
export async function registerWithEmail(
  email: string,
  password: string,
  profile: RegisterProfileInput
): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const result = await createUserWithEmailAndPassword(auth, email, password);
    const displayName = profile.displayName || profile.name || 'مستخدم';
    const phoneNumber = profile.phoneNumber || profile.phone || '';
    const names = splitName(displayName);

    const userProfile = defaultUserFields({
      id: result.user.uid,
      email,
      displayName,
      phoneNumber: phoneNumber ? formatAlgerianPhone(phoneNumber) : '',
      firstName: profile.firstName || names.firstName,
      lastName: profile.lastName ?? names.lastName,
      wilaya: profile.wilaya || '',
      commune: profile.commune || '',
      ...(profile.accountType ? { accountType: profile.accountType } : {}),
      profileComplete: profile.profileComplete ?? Boolean(profile.wilaya && profile.phoneNumber && profile.accountType),
    });
    
    await createUserProfile(userProfile);
    return userProfile;
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Process Google sign-in credential and ensure Firestore profile exists.
 */
async function processGoogleUser(firebaseUser: User): Promise<AuthUser> {
  let userProfile = await getUserProfile(firebaseUser.uid, false);

  if (!userProfile) {
    const displayName = firebaseUser.displayName || 'مستخدم جوجل';
    const photoURL = firebaseUser.photoURL;
    userProfile = defaultUserFields({
      id: firebaseUser.uid,
      email: firebaseUser.email || '',
      displayName,
      phoneNumber: firebaseUser.phoneNumber || '',
      isEmailVerified: firebaseUser.emailVerified,
      profileComplete: false,
      lastLoginAt: new Date().toISOString(),
      ...(photoURL ? { profileImageUrl: photoURL } : {}),
    });

    await createUserProfile(userProfile);
  } else {
    try {
      assertAccountAllowed(userProfile);
    } catch (blocked) {
      await signOutQuietly();
      throw blocked;
    }
    await updateUserProfile(userProfile.id, {
      lastLoginAt: new Date().toISOString(),
    });
    userProfile.lastLoginAt = new Date().toISOString();
  }

  return userProfile;
}

/**
 * Sign in with Google (popup, with redirect fallback when popup is blocked)
 */
export async function signInWithGoogle(): Promise<AuthUser> {
  try {
    const auth = getFirebaseAuth();
    const provider = new GoogleAuthProvider();
    provider.addScope('email');
    provider.addScope('profile');

    const result = await signInWithPopup(auth, provider);
    return processGoogleUser(result.user);
  } catch (error: unknown) {
    const firebaseError = error as { code?: string };
    if (firebaseError.code === 'auth/popup-blocked') {
      const auth = getFirebaseAuth();
      const provider = new GoogleAuthProvider();
      provider.addScope('email');
      provider.addScope('profile');
      await signInWithRedirect(auth, provider);
      throw new Error('جارٍ إكمال تسجيل الدخول عبر Google...');
    }
    throw new Error(mapAuthErrorToArabic(error as import('firebase/app').FirebaseError));
  }
}

/**
 * Handle Google redirect result after signInWithRedirect (call on app load).
 */
export async function handleGoogleRedirectResult(): Promise<AuthUser | null> {
  if (typeof window === 'undefined') return null;

  try {
    const auth = getFirebaseAuth();
    const result = await getRedirectResult(auth);
    if (!result?.user) return null;
    return processGoogleUser(result.user);
  } catch (error: unknown) {
    throw new Error(mapAuthErrorToArabic(error as import('firebase/app').FirebaseError));
  }
}

/**
 * Sign out current user
 */
export async function signOutUser(): Promise<void> {
  try {
    const auth = getFirebaseAuth();
    await signOut(auth);
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Send password reset email
 */
export async function sendPasswordReset(email: string): Promise<void> {
  try {
    const auth = getFirebaseAuth();
    await sendPasswordResetEmail(auth, email);
  } catch (error: any) {
    throw new Error(mapAuthErrorToArabic(error));
  }
}

/**
 * Set up auth state listener
 */
export function onAuthStateChange(callback: (user: User | null) => void): () => void {
  const auth = getFirebaseAuth();
  return onAuthStateChanged(auth, callback);
}

/**
 * Get current Firebase user
 */
export function getCurrentUser(): User | null {
  const auth = getFirebaseAuth();
  return auth.currentUser;
}

/**
 * Get user profile from Firestore
 */
export async function getUserProfile(uid: string, throwIfNotFound = true): Promise<AuthUser | null> {
  try {
    const firestore = getFirebaseFirestore();
    const userDoc = await getDoc(doc(firestore, 'users', uid));
    
    if (!userDoc.exists()) {
      if (throwIfNotFound) {
        throw new Error('ملف المستخدم غير موجود');
      }
      return null;
    }
    
    const data = fields(userDoc.data());
    const displayName = data['displayName'] || data['name'] || '';
    const phoneNumber = data['phoneNumber'] || data['phone'] || '';
    const names = splitName(displayName);

    const lastLoginAt = toIso(data['lastLoginAt']);

    return withAliases({
      id: data['id'] || uid,
      email: data['email'] || '',
      displayName,
      phoneNumber,
      firstName: data['firstName'] || names.firstName,
      lastName: data['lastName'] || names.lastName,
      ...(data['dateOfBirth'] ? { dateOfBirth: data['dateOfBirth'] } : {}),
      gender: data['gender'] || 'not_specified',
      wilaya: data['wilaya'] || '',
      commune: data['commune'] || '',
      ...(data['address'] ? { address: data['address'] } : {}),
      ...(data['profileImageUrl'] ? { profileImageUrl: data['profileImageUrl'] } : {}),
      isEmailVerified: data['isEmailVerified'] || false,
      isPhoneVerified: data['isPhoneVerified'] || false,
      listingsCount: data['listingsCount'] || 0,
      totalViews: data['totalViews'] || 0,
      totalContactClicks: data['totalContactClicks'] || 0,
      rating: data['rating'] || 0,
      reviewsCount: data['reviewsCount'] || 0,
      accountStatus: data['accountStatus'] || 'active',
      role: data['role'] || 'user',
      ...(data['accountType'] ? { accountType: data['accountType'] as AccountType } : {}),
      profileComplete:
        data['profileComplete'] ??
        Boolean(displayName?.trim() && phoneNumber?.trim() && data['wilaya'] && data['accountType']),
      isSubscribedToNewsletter: data['isSubscribedToNewsletter'] || false,
      memberSince: toIso(data['memberSince']) || data['memberSince'] || new Date().toISOString(),
      ...(lastLoginAt ? { lastLoginAt } : {}),
      ...(data['bio'] ? { bio: data['bio'] } : {}),
      ...(data['website'] ? { website: data['website'] } : {}),
      socialLinks: data['socialLinks'] || {},
      preferences: data['preferences'] || DEFAULT_PREFERENCES,
    });
  } catch (error: unknown) {
    if (error instanceof Error && !('code' in error)) throw error;
    throw new Error(mapFirebaseErrorToArabic(error as import('firebase/app').FirebaseError));
  }
}

/**
 * Create user profile in Firestore
 */
export async function createUserProfile(profile: AuthUser): Promise<void> {
  try {
    const firestore = getFirebaseFirestore();
    const payload = omitUndefined({
      ...profile,
      // Legacy fields for backward compatibility
      name: profile.displayName,
      phone: profile.phoneNumber,
      // Timestamps
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    } as Record<string, unknown>);
    await setDoc(doc(firestore, 'users', profile.id), payload);
  } catch (error: unknown) {
    if (error instanceof Error && !('code' in error)) throw error;
    throw new Error(mapFirebaseErrorToArabic(error as import('firebase/app').FirebaseError));
  }
}

/**
 * Update user profile in Firestore
 */
export async function updateUserProfile(uid: string, updates: Partial<AuthUser>): Promise<void> {
  try {
    const firestore = getFirebaseFirestore();

    const updateData: Record<string, unknown> = {
      ...omitUndefined(updates as Record<string, unknown>),
      updatedAt: serverTimestamp(),
    };

    if (updates.displayName || updates.name) {
      updateData['name'] = updates.displayName || updates.name;
      updateData['displayName'] = updates.displayName || updates.name;
    }
    if (updates.phoneNumber || updates.phone) {
      const raw = updates.phoneNumber || updates.phone || '';
      const normalized = formatAlgerianPhone(raw);
      updateData['phone'] = normalized;
      updateData['phoneNumber'] = normalized;
    }

    await updateDoc(doc(firestore, 'users', uid), updateData);
  } catch (error: unknown) {
    if (error instanceof Error && !('code' in error)) throw error;
    throw new Error(mapFirebaseErrorToArabic(error as import('firebase/app').FirebaseError));
  }
}